CREATE DATABASE anubis_dm_test1 COLLATE Latin1_General_CS_AS;
GO
CREATE DATABASE anubis_ldm_test1 COLLATE Latin1_General_CS_AS;
GO
CREATE DATABASE plankton_anubis_dm;
GO
CREATE DATABASE plankton_anubis_ldm;
GO

CREATE LOGIN [i2] WITH PASSWORD='i2', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [anubis] WITH PASSWORD='anubis', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [ssrs] WITH PASSWORD='ssrs', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [anubis_dm_test1]
GO
CREATE USER [i2] FOR LOGIN [i2] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [anubis] FOR LOGIN [anubis] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [ssrs] FOR LOGIN [ssrs] WITH DEFAULT_SCHEMA=[dbo];
GO

CREATE ROLE db_anubis_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::dbo TO db_anubis_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, REFERENCES TO db_anubis_role;
GO
CREATE ROLE db_mi_role;
GO
CREATE SCHEMA mi AUTHORIZATION [ssrs];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE ON schema::mi to db_mi_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION TO db_mi_role;
GO
GRANT EXECUTE, SELECT, VIEW DEFINITION ON schema::dbo TO db_mi_role;
GO
CREATE SCHEMA Tzdb AUTHORIZATION [dbo];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_anubis_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_mi_role;
GO

ALTER ROLE db_anubis_role ADD MEMBER i2;
GO
ALTER ROLE db_anubis_role ADD MEMBER anubis;
GO
ALTER ROLE db_mi_role ADD MEMBER [ssrs];
GO

USE [anubis_ldm_test1]
GO
CREATE USER [i2] FOR LOGIN [i2] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [anubis] FOR LOGIN [anubis] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [ssrs] FOR LOGIN [ssrs] WITH DEFAULT_SCHEMA=[dbo];
GO

CREATE ROLE db_anubis_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::dbo TO db_anubis_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, REFERENCES TO db_anubis_role;
GO
CREATE ROLE db_mi_role;
GO
CREATE SCHEMA mi AUTHORIZATION [ssrs];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE ON schema::mi to db_mi_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION TO db_mi_role;
GO
GRANT EXECUTE, SELECT, VIEW DEFINITION ON schema::dbo TO db_mi_role;
GO
CREATE SCHEMA Tzdb AUTHORIZATION [dbo];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_anubis_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_mi_role;
GO

ALTER ROLE db_anubis_role ADD MEMBER i2;
GO
ALTER ROLE db_anubis_role ADD MEMBER anubis;
GO
ALTER ROLE db_mi_role ADD MEMBER [ssrs];
GO

USE [plankton_anubis_dm]
GO
CREATE USER [i2] FOR LOGIN [i2] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [anubis] FOR LOGIN [anubis] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [ssrs] FOR LOGIN [ssrs] WITH DEFAULT_SCHEMA=[dbo];
GO

CREATE ROLE db_anubis_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::dbo TO db_anubis_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, REFERENCES TO db_anubis_role;
GO

CREATE ROLE db_mi_role;
GO
CREATE SCHEMA mi AUTHORIZATION [ssrs];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::mi to db_mi_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::dbo TO db_mi_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SYNONYM TO db_mi_role;
GO

CREATE SCHEMA Tzdb AUTHORIZATION [dbo];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_mi_role;
GO

ALTER ROLE db_anubis_role ADD MEMBER i2;
GO
ALTER ROLE db_anubis_role ADD MEMBER anubis;
GO
ALTER ROLE db_mi_role ADD MEMBER [ssrs];
GO

USE [plankton_anubis_ldm]
GO
CREATE USER [i2] FOR LOGIN [i2] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [anubis] FOR LOGIN [anubis] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE USER [ssrs] FOR LOGIN [ssrs] WITH DEFAULT_SCHEMA=[dbo];
GO

CREATE ROLE db_anubis_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::dbo TO db_anubis_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, REFERENCES TO db_anubis_role;
GO

CREATE ROLE db_mi_role;
GO
CREATE SCHEMA mi AUTHORIZATION [ssrs];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::mi to db_mi_role;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::dbo TO db_mi_role;
GO
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SYNONYM TO db_mi_role;
GO

CREATE SCHEMA Tzdb AUTHORIZATION [dbo];
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE, VIEW DEFINITION ON schema::Tzdb TO db_mi_role;
GO

ALTER ROLE db_anubis_role ADD MEMBER i2;
GO
ALTER ROLE db_anubis_role ADD MEMBER anubis;
GO
ALTER ROLE db_mi_role ADD MEMBER [ssrs];
GO

